name: Deploy Infraestructura AWS

on:
  workflow_dispatch: # Permite ejecutarlo manualmente desde GitHub Actions
  push:
    branches: [ "main" ]
    paths:
      - "scripts/**" # Se ejecuta si actualizas el script de infraestructura

jobs:
  build-infra:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      # 1. Actualizado a v4 para eliminar la advertencia de Node.js 20
      uses: actions/checkout@v4

    - name: Configurar credenciales AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Ejecutar script de AWS CLI
      run: |
        # 2. Instalar dos2unix para prevenir el error 127 por saltos de línea de Windows
        sudo apt-get update
        sudo apt-get install -y dos2unix
        
        # 3. Limpiar formato del archivo
        dos2unix ./scripts/crear-infra.sh
        
        # 4. Dar permisos y ejecutar con bash
        chmod +x ./scripts/crear-infra.sh
        bash ./scripts/crear-infra.sh